In [5]:
import pandas as pd
import numpy as np

In [9]:
import os

print(os.getcwd())

C:\Users\Acer\Desktop\Megha Project\Global Air Pollution Dataset\Notebook

In [11]:
import pandas as pd

df = pd.read_csv(
    "../data/raw data/global air pollution dataset.csv"
)

df.head()

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good

In [13]:
df.shape

(23463, 12)

In [15]:
df.isnull().sum()

Country               427
City                    1
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23463 entries, 0 to 23462
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             23036 non-null  object
 1   City                23462 non-null  object
 2   AQI Value           23463 non-null  int64
 3   AQI Category        23463 non-null  object
 4   CO AQI Value        23463 non-null  int64
 5   CO AQI Category     23463 non-null  object
 6   Ozone AQI Value     23463 non-null  int64
 7   Ozone AQI Category  23463 non-null  object
 8   NO2 AQI Value       23463 non-null  int64
 9   NO2 AQI Category    23463 non-null  object
 10  PM2.5 AQI Value     23463 non-null  int64
 11  PM2.5 AQI Category  23463 non-null  object
dtypes: int64(5), object(7)
memory usage: 2.1+ MB

In [19]:
df.columns.tolist()

['Country',
 'City',
 'AQI Value',
 'AQI Category',
 'CO AQI Value',
 'CO AQI Category',
 'Ozone AQI Value',
 'Ozone AQI Category',
 'NO2 AQI Value',
 'NO2 AQI Category',
 'PM2.5 AQI Value',
 'PM2.5 AQI Category']

In [23]:
df.duplicated().sum()

0

In [25]:
df[df["Country"].isna()].head(20)

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
535,NaN,Granville,30,Good,1,Good,30,Good,3,Good,25,Good
654,NaN,Kingston Upon Hull,33,Good,1,Good,17,Good,8,Good,33,Good
787,NaN,New Waterford,20,Good,1,Good,18,Good,9,Good,20,Good
801,NaN,Kingstown,163,Unhealthy,0,Good,25,Good,0,Good,163,Unhealthy
906,NaN,Nanakuli,30,Good,0,Good,27,Good,0,Good,30,Good
916,NaN,Lavagna,55,Moderate,1,Good,38,Good,2,Good,55,Moderate
968,NaN,Ladispoli,48,Good,1,Good,48,Good,2,Good,34,Good
985,NaN,Dong Hoi,55,Moderate,0,Good,26,Good,0,Good,55,Moderate
1139,NaN,Nettuno,53,Moderate,1,Good,53,Moderate,1,Good,23,Good
1169,NaN,Puebloviejo,71,Moderate,1,Good,16,Good,0,Good,71,Moderate
1247,NaN,Fiumicino,51,Moderate,2,Good,39,Good,7,Good,51,Moderate
1474,NaN,Nishinomiya,56,Moderate,2,Good,38,Good,5,Good,56,Moderate
1550,NaN,Carteret,56,Moderate,1,Good,29,Good,9,Good,56,Moderate
1609,NaN,Ercolano,48,Good,1,Good,48,Good,1,Good,30,Good
1627,NaN,Bolama,121,Unhealthy for Sensitive Groups,1,Good,24,Good,0,Good,121,Unhealthy for Sensitive Groups
1631,NaN,Bairiki,38,Good,0,Good,15,Good,0,Good,38,Good
1693,NaN,Broome,30,Good,1,Good,19,Good,0,Good,30,Good
1712,NaN,Cananeia,23,Good,0,Good,23,Good,0,Good,20,Good
1723,NaN,Cavite,74,Moderate,2,Good,27,Good,4,Good,74,Moderate
1792,NaN,Prince Rupert,31,Good,0,Good,31,Good,0,Good,6,Good

In [29]:
df[df["Country"].isna()]["City"].value_counts().head(20)

City
Granville            1
Nileshwar            1
Cleethorpes          1
Hendaye              1
Half Moon Bay        1
Alta                 1
Icod De Los Vinos    1
Rio Das Ostras       1
Rhyl                 1
Matsuura             1
Portoferraio         1
Chioggia             1
Conakry              1
Acapulco             1
Porto San Giorgio    1
Matinhos             1
Rameswaram           1
Isabela              1
Florianopolis        1
Iona                 1
Name: count, dtype: int64

In [35]:
df[df["City"].isna()]

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
2641,Israel,NaN,68,Moderate,1,Good,48,Good,4,Good,68,Moderate

In [73]:
df["Country"].nunique()

175

In [75]:
df["City"].nunique()

23462

In [81]:
df["AQI Category"].value_counts()

AQI Category
Good                              9936
Moderate                          9231
Unhealthy                         2227
Unhealthy for Sensitive Groups    1591
Very Unhealthy                     287
Hazardous                          191
Name: count, dtype: int64

In [87]:
df["Country"].value_counts().head(20)

Country
United States of America                                2872
India                                                   2488
Brazil                                                  1562
Germany                                                 1345
Russian Federation                                      1241
Italy                                                    979
France                                                   802
China                                                    795
Japan                                                    702
Mexico                                                   588
Spain                                                    425
United Kingdom of Great Britain and Northern Ireland     400
Poland                                                   389
Indonesia                                                379
Philippines                                              337
Pakistan                                                 307
Netherlands                                              298
Belgium                                                  284
Colombia                                                 250
Thailand                                                 246
Name: count, dtype: int64

In [95]:
df.describe().T

                   count       mean        std  min   25%   50%   75%    max
AQI Value        23463.0  72.010868  56.055220  6.0  39.0  55.0  79.0  500.0
CO AQI Value     23463.0   1.368367   1.832064  0.0   1.0   1.0   1.0  133.0
Ozone AQI Value  23463.0  35.193709  28.098723  0.0  21.0  31.0  40.0  235.0
NO2 AQI Value    23463.0   3.063334   5.254108  0.0   0.0   1.0   4.0   91.0
PM2.5 AQI Value  23463.0  68.519755  54.796443  0.0  35.0  54.0  79.0  500.0

In [97]:
for col in [
    "AQI Category",
    "CO AQI Category",
    "Ozone AQI Category",
    "NO2 AQI Category",
    "PM2.5 AQI Category"
]:
    print("\n", col)
    print(df[col].value_counts())

 AQI Category
AQI Category
Good                              9936
Moderate                          9231
Unhealthy                         2227
Unhealthy for Sensitive Groups    1591
Very Unhealthy                     287
Hazardous                          191
Name: count, dtype: int64

 CO AQI Category
CO AQI Category
Good                              23460
Moderate                              2
Unhealthy for Sensitive Groups        1
Name: count, dtype: int64

 Ozone AQI Category
Ozone AQI Category
Good                              21069
Moderate                           1445
Unhealthy for Sensitive Groups      491
Unhealthy                           405
Very Unhealthy                       53
Name: count, dtype: int64

 NO2 AQI Category
NO2 AQI Category
Good        23448
Moderate       15
Name: count, dtype: int64

 PM2.5 AQI Category
PM2.5 AQI Category
Good                              10208
Moderate                           9075
Unhealthy                          2129
Unhealthy for Sensitive Groups     1624
Very Unhealthy                      255
Hazardous                           172
Name: count, dtype: int64