In [1]:
import pandas as pd
import numpy as np 

df = pd.read_csv(
    "../data/processed data/clean_air_pollution.csv"
)

df.head()

,country,city,aqi_value,aqi_category,co_aqi_value,co_aqi_category,ozone_aqi_value,ozone_aqi_category,no2_aqi_value,no2_aqi_category,pm2_5_aqi_value,pm2_5_aqi_category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good

In [3]:
df.shape

(23462, 12)

In [5]:
df.isnull().sum()

country               0
city                  0
aqi_value             0
aqi_category          0
co_aqi_value          0
co_aqi_category       0
ozone_aqi_value       0
ozone_aqi_category    0
no2_aqi_value         0
no2_aqi_category      0
pm2_5_aqi_value       0
pm2_5_aqi_category    0
dtype: int64

In [13]:
features = [
    "country",
    "city",
    "co_aqi_value",
    "ozone_aqi_value",
    "no2_aqi_value",
    "pm2_5_aqi_value"
]

target = "aqi_category"

In [15]:
X = df[features]
y = df[target]

In [17]:
X.head()

,country,city,co_aqi_value,ozone_aqi_value,no2_aqi_value,pm2_5_aqi_value
0,Russian Federation,Praskoveya,1,36,0,51
1,Brazil,Presidente Dutra,1,5,1,41
2,Italy,Priolo Gargallo,1,39,2,66
3,Poland,Przasnysz,1,34,0,20
4,France,Punaauia,0,22,0,6

In [19]:
y.head()

0    Moderate
1        Good
2    Moderate
3        Good
4        Good
Name: aqi_category, dtype: object

In [21]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (23462, 6)
y shape: (23462,)

In [29]:
y.value_counts()

aqi_category
Good                              9936
Moderate                          9230
Unhealthy                         2227
Unhealthy for Sensitive Groups    1591
Very Unhealthy                     287
Hazardous                          191
Name: count, dtype: int64

In [27]:
y.value_counts(normalize=True) * 100

aqi_category
Good                              42.349331
Moderate                          39.340210
Unhealthy                          9.491944
Unhealthy for Sensitive Groups     6.781178
Very Unhealthy                     1.223255
Hazardous                          0.814082
Name: proportion, dtype: float64

In [33]:
model_df = df[features + [target]].copy()

model_df.to_csv(
    "../data/processed data/model_data.csv",
    index=False
)

In [36]:
model_df.head()

,country,city,co_aqi_value,ozone_aqi_value,no2_aqi_value,pm2_5_aqi_value,aqi_category
0,Russian Federation,Praskoveya,1,36,0,51,Moderate
1,Brazil,Presidente Dutra,1,5,1,41,Good
2,Italy,Priolo Gargallo,1,39,2,66,Moderate
3,Poland,Przasnysz,1,34,0,20,Good
4,France,Punaauia,0,22,0,6,Good