In [1]:
import pandas as pd
import joblib

In [3]:
model = joblib.load(
    "../models/aqi_category_model.pkl"
)

print("Model loaded successfully!")

Model loaded successfully!

In [9]:
new_data = pd.DataFrame({
    "country": ["India"],
    "city": ["Mumbai"],
    "co_aqi_value": [20],
    "ozone_aqi_value": [40],
    "no2_aqi_value": [30],
    "pm2_5_aqi_value": [150]
})

new_data

,country,city,co_aqi_value,ozone_aqi_value,no2_aqi_value,pm2_5_aqi_value
0,India,Mumbai,20,40,30,150

In [11]:
prediction = model.predict(new_data)

print("Predicted AQI Category:", prediction[0])

Predicted AQI Category: Unhealthy

In [13]:
probabilities = model.predict_proba(new_data)

probability_df = pd.DataFrame(
    probabilities,
    columns=model.classes_
)

probability_df

,Good,Hazardous,Moderate,Unhealthy,Unhealthy for Sensitive Groups,Very Unhealthy
0,0.0,0.015,0.01,0.76,0.015,0.2